[package]
edition = "2021"
name    = "qed_dsol_ibc_node_common"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow     = { workspace = true }
bytemuck = "1.25.1"
serde      = { workspace = true }
borsh      = { workspace = true }
serde_json      = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
qed_dsol_bridge_core = { path = "../qed_dsol_bridge_core" }

bitcoin = { workspace = true }

tokio = { workspace = true }
futures = { workspace = true }


fred = { workspace = true }
doge-light-client = { workspace = true, features = ["serialize_serde"] }
reqwest = { workspace = true }
psy-doge-bridge-helper = { path = "../../dlc-lib/doge-light-client-workspace/psy-doge-bridge-helper" }
doge-bridge-client = { path = "../../psy-doge-solana-bridge/clients/rust" }
solana-sdk = { workspace = true }
solana-client = { workspace = true }
speedy = "0.8.7"
clap = { workspace = true }